### ISSUE TITLE
IAM Roles have hard-coded names, cannot apply module multiple times

### ISSUE THREAD

**Issue by igoralveslima** [clowdhaus/terraform-aws-dms#11]
**Describe the bug**
IAM resources have hard-coded names, which prevents users from applying this module multiple times in a single account

https://github.com/clowdhaus/terraform-aws-dms/blob/main/main.tf#L47
https://github.com/clowdhaus/terraform-aws-dms/blob/main/main.tf#L66

**To Reproduce**
- Apply module to create DMS migration for service A in account 1
- Apply module to create DMS migration for service B in account 1
- AWS API errors "EntityAlreadyExists: Role with name dms-cloudwatch-logs-role already exists."

**Expected behavior**
- Resources should include a randomly generated identifier
- Allow users to override the IAM resource names

**Screenshots**
- N/A

**Desktop (please complete the following information):**
- N/A

**Smartphone (please complete the following information):**
- N/A

**Additional context**
- N/A

**Comment by bryantbiggs** [comment]
yes, this is an AWS requirement. I will agree it is rather odd and there are numerous issues reported on this, but it is what is required by the AWS API in order for DMS to function properly - https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Security.html#CHAP_Security.APIRole
