### ISSUE TITLE
Start Replication Task

### ISSUE THREAD

**Issue by ddvdozuki** [clowdhaus/terraform-aws-dms#4]
This module works well but it leaves the replication task in a "ready" state, not started. Is there any way to start It afterwards? 

**Describe alternatives you've considered**
An alternative I have to use now is a null_resource local-exec provisioner that uses the API to start and stop the task.

**Comment by bryantbiggs** [comment]
I hope to avoid the use of the null resource here so lets track upstream native support https://github.com/hashicorp/terraform-provider-aws/issues/2083

**Comment by bryantbiggs** [comment]
should be out later today with v4.6.0 of the provider https://github.com/hashicorp/terraform-provider-aws/pull/23692 (provided they release today per usual)

**Comment by ddvdozuki** [comment]
I saw that, excellent news 👍
